// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxtl_UIVvo30aH2EdooEkUfyE-5BLPFc',
    appId: '1:120472047741:web:b1f80cc0400cc4370b2114',
    messagingSenderId: '120472047741',
    projectId: 'fitness-workout-tracker-app',
    authDomain: 'fitness-workout-tracker-app.firebaseapp.com',
    storageBucket: 'fitness-workout-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATf0R9lFXTS8Yzqb4p0V96zcDLPNpoCbo',
    appId: '1:120472047741:android:2975c3c2c8e214fd0b2114',
    messagingSenderId: '120472047741',
    projectId: 'fitness-workout-tracker-app',
    storageBucket: 'fitness-workout-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBye1xPAh3PN6-GAgjIa1qr_ACDlMMyn74',
    appId: '1:120472047741:ios:0380e743983a133e0b2114',
    messagingSenderId: '120472047741',
    projectId: 'fitness-workout-tracker-app',
    storageBucket: 'fitness-workout-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBye1xPAh3PN6-GAgjIa1qr_ACDlMMyn74',
    appId: '1:120472047741:ios:0380e743983a133e0b2114',
    messagingSenderId: '120472047741',
    projectId: 'fitness-workout-tracker-app',
    storageBucket: 'fitness-workout-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxtl_UIVvo30aH2EdooEkUfyE-5BLPFc',
    appId: '1:120472047741:web:2d3c54337692087f0b2114',
    messagingSenderId: '120472047741',
    projectId: 'fitness-workout-tracker-app',
    authDomain: 'fitness-workout-tracker-app.firebaseapp.com',
    storageBucket: 'fitness-workout-tracker-app.firebasestorage.app',
  );
}
